services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - '.:/rails'
      - 'app-gems:/usr/local/bundle/gems'

  database:
    image: 'postgres:16.3'
    env_file: .env
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    ports:
      - '5432:5432'
    volumes:
      - 'app-postgres:/var/lib/postgresql/data'

volumes:
  app-gems:
  app-postgres:
